version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: external
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: icons
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: