version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: external
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: icons
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile.frontend
    ports:
      - "57072:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=external
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=icons
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: