version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: external
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: icons
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=external
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=icons
      - PORT=3000
    depends_on:
      - db


volumes:
  db_data: