generate: 
	protoc --go_out=./broker/gen/volunteer --go-grpc_out=./broker/gen/volunteer ./broker/proto/volunteer.proto
	protoc --go_out=./volunteer/gen/volunteer --go-grpc_out=./volunteer/gen/volunteer ./volunteer/proto/volunteer.proto