// Enum dla kategorii pomocy
export enum Categories {
  ZAKUPY = "ZAKUPY",
  LEKI = "LEKI",
  SPRZATANIE = "SPRZATANIE",
  SPACER = "SPACER",
  TRANSPORT = "TRANSPORT",
  POSILKI = "POSILKI",
  OPIEKA = "OPIEKA",
  ROZMOWA = "ROZMOWA",
  NAPRAWA = "NAPRAWA",
  TECHNOLOGIA = "TECHNOLOGIA",
  OGROD = "OGROD",
  PISANIE = "PISANIE",
}

// Enum dla województw w Polsce bez polskich znaków
export enum Regions {
  DOLNOSLASKIE = "DOLNOSLASKIE",
  KUJAWSKO_POMORSKIE = "KUJAWSKO_POMORSKIE",
  LUBELSKIE = "LUBELSKIE",
  LUBUSKIE = "LUBUSKIE",
  MALOPOLSKIE = "MALOPOLSKIE",
  MAZOWIECKIE = "MAZOWIECKIE",
  OPOLSKIE = "OPOLSKIE",
  PODKARPACIE = "PODKARPACIE",
  PODLASKIE = "PODLASKIE",
  POMORSKIE = "POMORSKIE",
  SLASKIE = "SLASKIE",
  SWIETOKRZYSKIE = "SWIETOKRZYSKIE",
  WARMIANSKO_MAZURSKIE = "WARMIANSKO_MAZURSKIE",
  WIELKOPOLSKIE = "WIELKOPOLSKIE",
  ZACHODNIOPOMORSKIE = "ZACHODNIOPOMORSKIE",
}
